// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm7eCc0jSz7E1Jy2SIlMPMBnzuFmmgI-I',
    appId: '1:206286600346:web:abee1f97bb1588a92c4723',
    messagingSenderId: '206286600346',
    projectId: 'droidkaigi-2022',
    authDomain: 'droidkaigi-2022.firebaseapp.com',
    storageBucket: 'droidkaigi-2022.appspot.com',
    measurementId: 'G-SNLEC9HFGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_8T9F8kVvjv41taur-uUeFsndNd-2Yu4',
    appId: '1:206286600346:android:693d75517f669a472c4723',
    messagingSenderId: '206286600346',
    projectId: 'droidkaigi-2022',
    storageBucket: 'droidkaigi-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAVLoXeNlSvLOJBNDBH0zEq4xV8nbP0jE',
    appId: '1:206286600346:ios:b9dcdaec56345f472c4723',
    messagingSenderId: '206286600346',
    projectId: 'droidkaigi-2022',
    storageBucket: 'droidkaigi-2022.appspot.com',
    iosClientId: '206286600346-dmacb46o0kaf6v51o4do2i7ahk402dtm.apps.googleusercontent.com',
    iosBundleId: 'com.dreamwalker.flutterDroidkaigi2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAVLoXeNlSvLOJBNDBH0zEq4xV8nbP0jE',
    appId: '1:206286600346:ios:b9dcdaec56345f472c4723',
    messagingSenderId: '206286600346',
    projectId: 'droidkaigi-2022',
    storageBucket: 'droidkaigi-2022.appspot.com',
    iosClientId: '206286600346-dmacb46o0kaf6v51o4do2i7ahk402dtm.apps.googleusercontent.com',
    iosBundleId: 'com.dreamwalker.flutterDroidkaigi2022',
  );
}
